# Generated by Django 3.2 on 2021-04-27 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_pub_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['pub_date']},
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='created_on',
            new_name='pub_date',
        ),
    ]
